development:
  adapter: postgresql
  encoding: unicode
  database: tfc_development
  pool: 5
  username: tfc_development
  password: tfc_development

test:
  adapter: postgresql
  encoding: unicode
  database: tfc_test
  pool: 5
  username: tfc_test
  password: tfc_test
