development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: postgresql
  database: tfc_development
  username: tfc_development
  password: tfc_development

test:
  adapter: postgresql
  encoding: unicode
  database: tfc_test
  pool: 5
  host: postgresql
  username: tfc_test
  password: tfc_test
